# generated by datamodel-codegen:
#   filename:  PublishBid_schema.json
#   timestamp: 2024-03-07T12:57:12+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class CreatedDateTime(BaseModel):
    time: str = Field(..., title='Time')


class MarketRole(str, Enum):
    buyer = 'buyer'
    seller = 'seller'


class Price(BaseModel):
    price: float = Field(..., title='Price')


class Quantity(BaseModel):
    quantity: float = Field(..., title='Quantity')


class PublishBid(BaseModel):
    bidID: str = Field(..., description='...', title='Bidid')
    bidCreatedDateTime: CreatedDateTime = Field(
        ..., description='Date and time that this Bid was created'
    )
    expectedPrice: Price
    expectedQuantity: Quantity
    marketRole: MarketRole = Field(
        ...,
        description='An identification of a party acting in a electricity market business process',
    )
    refMarketParticipant: str = Field(
        ..., description='...', title='Refmarketparticipant'
    )
