# generated by datamodel-codegen:
#   filename:  MarketParticipant_schema.json
#   timestamp: 2024-03-07T12:57:12+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class MarketParticipant(BaseModel):
    id: str = Field(..., description='Entity ID of MarketParticipant', title='Id')
    type: str = Field(..., description='Entity type of MarketParticipant', title='Type')
    buildingName: str = Field(..., description="Building's name", title='Buildingname')
    userID: str = Field(
        ..., description='The user name for the Building', title='Userid'
    )
    refActiveBid: str = Field(
        ..., description='Entity ID of relevant active bid', title='Refactivebid'
    )
    refTransaction: str = Field(
        ...,
        description='Entity ID of relevant Transaction result',
        title='Reftransaction',
    )
